- name: Set Admin password to avoid Sysprep prompt
  community.vmware.vmware_vm_shell:
    hostname: "{{ vmware.vcenter_hostname }}"
    username: "{{ vmware.vcenter_username }}"
    password: "{{ vmware.vcenter_password }}"
    validate_certs: false
    vm_id: "{{ cloned_vm_name }}"
    vm_username: "{{ admin_username }}"
    vm_password: "{{ admin_password }}"
    vm_shell: "powershell.exe"
    vm_shell_args: |
      -Command "Set-LocalUser -Name 'Administrator' -Password (ConvertTo-SecureString -AsPlainText 'NewPassword123!' -Force)"
    wait_for_process: true
  delegate_to: localhost

  